### ISSUE TITLE
MacOs 10.14 Mojave

### ISSUE THREAD

**Issue by Retriev3r** [iamjaneto/finito-app#1]
Hi!
On macOS 10.14 Mojave all screens are changed by Finito, even if the checkbox for "all screens" is not checked. If I set an static image as background on screen 2 for example. Finito will change it a few seconds later.
Could you please fix this?
Thank you,
Ben

**Comment by iamjaneto** [comment]
After several tests and without apparent code errors, I updated the dependencies and it seems that it no longer occurs, try with the [new release](https://github.com/iamjaneto/finito-app/releases/tag/1.2.1).

Thanks!

**Comment by Retriev3r** [comment]
Thank you.
I no longer have Mojave installed, because several apps wouldn't work. I am on High Sierra now.
